### ISSUE TITLE
How can I get the pickle files for training and validation?

### ISSUE THREAD

**Issue by LISI0037** [DLR-RM/UMF#1]
Hello,
Your work is great and very interesting. However, when I was running your project, I met some problems. The config_base.yaml file mentions two pickle files:

```
train_file: training_queries_baseline.pickle
val_file: validation_queries_baseline.pickle
```
Could you give any preprocessing scripts that should be used to create these files or how to generate these pickle files from the raw dataset?

**Comment by albertogarci** [comment]
Thanks for your interest. For the RobotCar dataset you can use the same steps defined in PointNetVLAD and MinkLocMultimodal to download and preprocess the data, for any other dataset you will need to define your own custom logic.

**Comment by bobododosjl** [comment]
How to define the custom logic of etna dataset？
