### ISSUE TITLE
Some bugs of the Evaluation

### ISSUE THREAD

**Issue by LISI0037** [DLR-RM/UMF#2]
Your work is great.
But I found some bugs when I'm trying to run it. 
eval/evaluate.py,  line 256-263, how/layers/dim_reduction do not have load_initialization
` if hasattr(model, 'lit'):
        print('-> Loading initialization values for lit and lit3d')
        model.lit.reduction_layer.load_initialization(mi, Pi)
        model.lit3d.reduction_layer.load_initialization(mp, Pp)
    elif hasattr(model, 'lt'):
        print('-> Loading initialization values for lt and lt3d')
        model.lt.reduction_layer.load_initialization(mi, Pi)
        model.lt3d.reduction_layer.load_initialization(mp, Pp)`
And /models/UMF/utils/lit.py, line 46 
`self.reduction_layer = layers.dim_reduction.LinearDimReduction(dim=out_dim, input_dim=dim)`
also, how/layers/dim_reduction do not have LinearDimReduction
/models/UMF/utils/lit3d.py, line 48
`self.reduction_layer = layers.dim_reduction.LinearDimReduction(dim=out_dim, input_dim=dim)`
And the evaluate.py can't work because of the bugs.

**Comment by albertogarci** [comment]
Please try using the following [version](https://github.com/albertogarci/how.git) which includes the missing classes.
